print("Hello World!")
print("Hey look a parrots!")
print("Hey look a kitten!")
print("Come back, kitten!")
print("kittehs can be monsters.")
print("I see a turtle!")
print("Oh, no! The kitten turned into a turtle!)